//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GourmetObjective.CLI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GourmetObjective.CLI.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pense em um prato que gosta.
        /// </summary>
        internal static string PenseEmUmPrato {
            get {
                return ResourceManager.GetString("PenseEmUmPrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} é ________ mas {1} não: .
        /// </summary>
        internal static string PerguntaDiferencialEntre2Pratos {
            get {
                return ResourceManager.GetString("PerguntaDiferencialEntre2Pratos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qual prato você pensou? .
        /// </summary>
        internal static string PerguntaQualPratoPensou {
            get {
                return ResourceManager.GetString("PerguntaQualPratoPensou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O prato que você pensou é {0}? .
        /// </summary>
        internal static string PratoQuePensou {
            get {
                return ResourceManager.GetString("PratoQuePensou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resposta inválida. Valores válidos: &apos;S&apos; para SIM, &apos;N&apos; para NÃO..
        /// </summary>
        internal static string RespostaBoolInvalida {
            get {
                return ResourceManager.GetString("RespostaBoolInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resposta inválida..
        /// </summary>
        internal static string RespostaStringInvalida {
            get {
                return ResourceManager.GetString("RespostaStringInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acertei de novo!.
        /// </summary>
        internal static string Vitoria {
            get {
                return ResourceManager.GetString("Vitoria", resourceCulture);
            }
        }
    }
}
